
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;

public class adminlogin extends javax.swing.JFrame {
    private String captchaCode;

    private String generateCaptcha() {
    // Generate a random 6-character alphanumeric code
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < 6; i++) {
        int index = (int) (chars.length() * Math.random());
        sb.append(chars.charAt(index));
    }
    return sb.toString();
    
}
 private void setUpCaptcha() {
        captchaCode = generateCaptcha();
        cla.setText(captchaCode);
    }


    private PreparedStatement pst;
    
    public adminlogin() {
        initComponents();
        captcha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setUpCaptcha();
             
        try
       {
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/libraryDB","root","iisc");
           //stm=con.createStatement();
           if(con!=null)
           {
               System.out.println("Successfully connected");
           }
       }
       catch(Exception e)
       {
           System.out.println("not connected");
           e.printStackTrace();
           
       }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        show = new javax.swing.JCheckBox();
        lcap = new javax.swing.JLabel();
        cla = new javax.swing.JLabel();
        captcha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Admin Login Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 30, 342, 54);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 130, 89, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 140, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 200, 100, 25);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(700, 200, 130, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 430, 120, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 430, 120, 30);

        show.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(690, 270, 160, 25);

        lcap.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lcap.setText("Captcha");
        getContentPane().add(lcap);
        lcap.setBounds(540, 270, 70, 21);

        cla.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        cla.setForeground(new java.awt.Color(0, 102, 102));
        cla.setText("CAPTCHA");
        cla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cla);
        cla.setBounds(530, 310, 122, 50);
        getContentPane().add(captcha);
        captcha.setBounds(700, 320, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup-library-icon.png"))); // NOI18N
        jLabel4.setText(".");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 110, 1110, 580);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        getContentPane().add(jButton3);
        jButton3.setBounds(820, 430, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password= jPasswordField1.getText();
        
        try
        {
           
            
            if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill out Username");
        }
        else if(jPasswordField1.getText().equals( ""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill out your Password");
        }
        else if(captcha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the CAPTCHA code");
        } else if(!captcha.getText().equals(captchaCode)) {
            JOptionPane.showMessageDialog(this, "Invalid CAPTCHA code");
            captcha.setText("");
        }
        else{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/libraryDB","root","iisc");
            Statement stm=con.createStatement();
           
            
            
                if(jTextField1.getText().equals(""))
                    JOptionPane.showMessageDialog(this, "please enter username");
                else if(jPasswordField1.getText().equals(""))
                    JOptionPane.showMessageDialog(this, "password is required");
                
                String query="SELECT * FROM adminlogin WHERE username = '"+jTextField1.getText()+"' and password = '"+jPasswordField1.getText()+"'";
                ResultSet rs=stm.executeQuery(query);
                //JOptionPane.showMessageDialog(this,"Login Successfully");
        
                while(rs.next())
                {
                   
                    MainLayer mn=new MainLayer();
                    mn.setVisible(true);
                    dispose();
                }   
                jTextField1.setText("");
                jPasswordField1.setText("");
                 
                this.setVisible(false);
                //}
        }
        }
        catch(SQLException e)
        {
            if(e.getErrorCode()==1062)
                JOptionPane.showMessageDialog(this,"AdminId is a primary key, duplicate entry is not allowed\nIt should be unique");
            else
                JOptionPane.showMessageDialog(this,"connection error");
         
        }            
                
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomePage h=new HomePage();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if (show.isSelected())
         {
            jPasswordField1.setEchoChar((char) 0); // Show password characters
        } 
        else 
        {
         jPasswordField1.setEchoChar('*'); // Hide password characters
        }
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captcha;
    private javax.swing.JLabel cla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lcap;
    private javax.swing.JCheckBox show;
    // End of variables declaration//GEN-END:variables
}
