
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jegat
 */
public class Stulogin extends javax.swing.JFrame {
    
private String captchaCode;
// Method to generate a random CAPTCHA code
    private String generateCaptcha() {
    // Generate a random 6-character alphanumeric code
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < 6; i++) {
        int index = (int) (chars.length() * Math.random());
        sb.append(chars.charAt(index));
    }
    return sb.toString();
    
}
 private void setUpCaptcha() {
        captchaCode = generateCaptcha();
        cla.setText(captchaCode);
    }

    
    public Stulogin() {
        initComponents();
        {
            captcha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

             setUpCaptcha();
             
            
    
        }
    }
    
    /*private void initComponents() {
       cla = new javax.swing.JLabel();
       captcha = new javax.swing.JTextField();
       lcap = new javax.swing.JLabel();
    }
*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lcap = new javax.swing.JLabel();
        cla = new javax.swing.JLabel();
        captcha = new javax.swing.JTextField();
        show = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 3, 18)); // NOI18N
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 160, 130, 22);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 3, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 220, 91, 29);

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STUDENT LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(144, 20, 443, 54);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(510, 210, 187, 40);

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(510, 150, 187, 40);

        jButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 490, 153, 43);

        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 490, 109, 43);

        lcap.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lcap.setText("Captcha");
        getContentPane().add(lcap);
        lcap.setBounds(320, 330, 130, 25);

        cla.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        cla.setForeground(new java.awt.Color(0, 102, 102));
        cla.setText("CAPTCHA");
        cla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cla);
        cla.setBounds(320, 390, 106, 36);
        getContentPane().add(captcha);
        captcha.setBounds(520, 330, 186, 30);

        show.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(510, 270, 187, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stuloog.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 280, 170);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 0, 440, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomePage m=new HomePage();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
       
    /*
    public void actionPerformed(ActionEvent evt) {
                registerActionPerformed(evt);
              
            }

    private void registerActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        });

        show.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
    */
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            
            if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill out Username");
        }
        else if(jPasswordField1.getText().equals( ""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill out your Password");
        }
        else if(captcha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the CAPTCHA code");
        } else if(!captcha.getText().equals(captchaCode)) {
            JOptionPane.showMessageDialog(this, "Invalid CAPTCHA code");
            captcha.setText("");
        }
        else
        {    
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/libraryDB","root","iisc");
            Statement stm=con.createStatement();
            
        
        
        
                String username = jTextField1.getText();
                String password= jPasswordField1.getText();
               // String password = new String(passwordChars);  
                String query="SELECT * FROM student WHERE stuid = '"+jTextField1.getText()+"' and passwd = '"+jPasswordField1.getText()+"'";
                ResultSet rs=stm.executeQuery(query);
                 
                while(rs.next())
                {
                    StudentView mn=new StudentView();
                    mn.setVisible(true);
                    dispose();
                }
        }
        }
        catch(Exception e)
        {
            
             JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
             jTextField1.setText("");
             jPasswordField1.setText("");
                 
                this.setVisible(false);
        }            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if (show.isSelected())
         {
            jPasswordField1.setEchoChar((char) 0); // Show password characters
        } 
        else 
        {
         jPasswordField1.setEchoChar('*'); // Hide password characters
        }
    }//GEN-LAST:event_showActionPerformed
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stulogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stulogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stulogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stulogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stulogin().setVisible(true);
            }
        });
    }
    //private javax.swing.JLabel lcap;
    //private javax.swing.JTextField captcha;
    //private javax.swing.JLabel cla;
    //private javax.swing.JCheckBox show;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captcha;
    private javax.swing.JLabel cla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lcap;
    private javax.swing.JCheckBox show;
    // End of variables declaration//GEN-END:variables
}
